services:
  app:
    build:
      dockerfile: ./Dockerfile
    command: ['python', 'manage.py', 'runserver', '0.0.0.0:8000']
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    volumes:
      - ./myshop/web/static:/app/web/static
      - ./myshop/web/media:/app/web/media
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: myshopfittin
      POSTGRES_USER: myshop_user
      POSTGRES_PASSWORD: fittin-test
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pg_data:

